Shared SSO
mixpanel/docs-legacy pull request #1220
Opened 2024-07-08 22:02 UTC by pjboudrx

2024-07-10 02:23 UTC, kurbycchua requested changes
See my comments

2024-07-10 02:23 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +If you have multiple Mixpanel Organizations with separate billing accounts, but need to share SSO settings and email domains for login, you can share those settings with an "Admin" Organization.
add link to "Organizations" for the line that says "If you have multiple Mixpanel Organizations" 

[Organizations](/docs/orgs-and-projects/organizations)

2024-07-10 02:23 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +An "Admin" Organization is a special type of Organization that contains Single Sign-On settings and Claimed Domains. It can have users, but these will typically be administrative users.
per DJ: can we be more assertive / opinionated here? IIUC, we don't recommend any users in this org unless they're administrative users who are responsible for configuring SSO / other admin settings?

2024-07-10 02:23 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +An "Admin" Organization is different from a regular Organization in that it will not have Projects, Teams, a Plan or Billing, or Service Accounts. Other than administrators, Users will not see the Ad
By "Users" do we mean other Org Members? Just trying to see if we can be consistent with terminologies per the Org Roles we have: https://docs.mixpanel.com/docs/orgs-and-projects/roles-and-permissions#organization-roles.

Also when we say administrator I am guessing that includes Org Owners. So we need to be clear and consistent with terminologies as we do get these type of questions as CSA where a customer would ask of that means only Admin and not Owner?

2024-07-10 02:23 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +> ❗ If you use Azure for SSO, contact Mixpanel before migrating, due to constraints with “Issuer URL” and “Identifier (Entity ID)”
maybe we could link "contact Mixpanel" to https://mixpanel.com/get-support

2024-07-10 02:23 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +Any Organization linked to an Admin Organization will use the Single Sign-On settings from that Admin Organization - and Single Sign-On settings or Claimed Domains the first Organization may have had
just thinking instead of saying "first" do we want to start say using terminology like "Linked" Organization or "Child" Organization?

2024-07-10 02:23 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +SSO settings and Claimed Domains are managed in the Admin Organization. Administrative users who manage SSO settings in the Admin Organization do not need to be members of the Linked Organization(s),
same comment for "Administrative" users here - we need to start defining what this means up front (ie Administrative means Owners + Admins Org Roles)?

2024-07-10 02:23 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +## Differences From Single-Organization SSO
So because I've been involved in the Admin SSO project I understand what this table means, but as an end-user I would not understand what this table is trying to say. A suggestion would perhaps to have some textual description under the table to explain what we mean, example:

1. SSO Configuration and Claiming of Domains for Non-Linked Organizations are configured within the Organization itself; whereas for Organizations Linked to a "Admin" Organization, these settings are configured at the "Admin" Organization level and shared across each Linked Organization.
2. SCIM concept of "Groups" for Non-Linked Organizations maps to Mixpanel [Teams](/docs/orgs-and-projects/roles-and-permissions#teams); whereas for "Admin" Organizations this would be mapped to Linked Organizations. See more details below

2024-07-10 02:23 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +Overview:
We should have screenshots for this to guide users on the steps?

2024-07-10 02:23 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +With Shared SSO, the SCIM process works a little differently. Users are pushed to the Admin Organization. Groups in the IDP are pushed to Organizations Linked to the Admin Organization. Groups are ma
Is it purely based on "name" and not ID? For Teams, I recall it uses the internal team ID and not the name to match

2024-07-10 02:23 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +## Migrating To Shared SSO
per DJ "any pictures easy to add to "Migrating To Shared SSO" section?". Understand that each IDP would be different but at least for those steps where it's Mixpanel side we should maybe have some screenshot?

2024-07-10 02:23 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +If you have Single Sign-On configured for an Organization, and want to use the same email domains with Shared SSO, you will need to migrate.
maybe merge this 2 paragraph together as:

If you have Single Sign-On configured for an Organization, and want to use the same email domains with a Shared SSO; you will need to follow these steps to migrate and minimize the time Single Sign-On is unavailable for your users.

2024-07-10 02:23 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +Following these steps in this order will minimize the time Single Sign-On is unavailable for your users.
see previous comment

2024-07-10 02:23 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +2. Set up SSO for the Admin Organization and configure an application in your IDP to match
guessing when we say "match" is to mapped it to the Admin Org? Might want state that explicitly? so like

2. Set up SSO for the Admin Organization and configure an application in your IDP with the corresponding settings. You can refer to the [Single Sign-on Overview](/docs/access-security/single-sign-on/overview) section in our docs or to the respective IDP docs for [Azure](/docs/access-security/single-sign-on/azure) or [Okta](/docs/access-security/single-sign-on/okta)

2024-07-10 02:23 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +3. Assign users in to the app in your IDP who will use Mixpanel in any Organization
Not quite sure I understand this step but I think what you are trying to say is 

3. In your IDP, assign all users (who will be using Mixpanel in any Linked Organization) into the newly configured app

2024-07-10 02:23 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +5. Link the original Organization to the Admin Organization
We need screenshots for this

2024-07-10 02:23 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +    1. This will cause the existing SSO set up to stop working
It's weird to have this like just 1. without a 2. might just want to put it as a 

>  This will cause the existing SSO set up to stop working

2024-07-10 02:23 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +6. Transfer claimed Domains from the original Organization to the Admin Organization
Do we perhaps as a step before want them to note down the domains they have claimed under the Child Orgs? I can't remember if we start to hide them when a Org gets linked?

2024-07-10 02:23 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +8. (optional) Finish setting up SCIM
For users who use Groups as Teams before they link an Org, any steps we need to advise them?

2024-07-10 02:23 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +    1. Establish a Group in your IDP for the users who have access to the original Organization
Maybe have these as bullets instead of like numbers again?

2024-07-10 21:56 UTC, pjboudrx commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +An "Admin" Organization is a special type of Organization that contains Single Sign-On settings and Claimed Domains. It can have users, but these will typically be administrative users.
The caveat is SCIM: users will be added to the Admin Org as part of the SCIM process. I'll find a way to phrase that.

2024-07-10 21:57 UTC, pjboudrx commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +An "Admin" Organization is different from a regular Organization in that it will not have Projects, Teams, a Plan or Billing, or Service Accounts. Other than administrators, Users will not see the Ad
Good points - yes, this means Org Members. I'll clarify. And yes, administrators includes Org Admins

2024-07-10 21:58 UTC, pjboudrx commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +Any Organization linked to an Admin Organization will use the Single Sign-On settings from that Admin Organization - and Single Sign-On settings or Claimed Domains the first Organization may have had
Yes, good catch.

2024-07-10 22:00 UTC, pjboudrx commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +5. Link the original Organization to the Admin Organization
The challenge there is that we can't screenshot all of the IDPs, and these are very high-level steps that would involve several screenshots in some cases. Much of what we show here would duplicate what we have documented for these steps elsewhere. I can link to those other docs, and I'll see what screenshots I can include (without having dozens)

2024-07-11 03:07 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +5. Link the original Organization to the Admin Organization
agree I was more thinking along the lines of just screenshots for the steps where it's mixpanel side, just to give users a rough idea where in Mixpanel it is configure. Then for those steps on the IDP side we should refer them to their IDP docs or the relevant docs we have like Okta and Azure

2024-07-11 23:47 UTC, pjboudrx commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +SSO settings and Claimed Domains are managed in the Admin Organization. Administrative users who manage SSO settings in the Admin Organization do not need to be members of the Linked Organization(s),
I this case, I've defined it as "users who manage SSO settings;" the technical MP role values aren't the key point.

2024-07-11 23:49 UTC, pjboudrx commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +## Differences From Single-Organization SSO
Yeah, I was trying to have a clear visual representation of what's different. There's a lot of text here, already. The point is to add some context for end users unfamiliar with the concept.

2024-07-16 01:18 UTC, pjboudrx commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +Overview:
Added.

2024-07-16 01:20 UTC, pjboudrx commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +5. Link the original Organization to the Admin Organization
I've expanded the steps and added screenshots + links

2024-07-16 01:22 UTC, pjboudrx commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +With Shared SSO, the SCIM process works a little differently. Users are pushed to the Admin Organization. Groups in the IDP are pushed to Organizations Linked to the Admin Organization. Groups are ma
The initial linking is all determined by the name. Consider this scenario: if you have a group in the IDP as well as a team, the way that the IDP matches them is by name. The IDP *does* keep a record of the team ID to know they are linked, but that is not how it is determined. 

In the case of a Linked Organization, it works like an existing Mixpanel Team - the IDP says "do you have a group (or equivalent) with this name? Because we don't want to tied the Organization Name to something that might have other reasons to change, we added the "SCIM Name".

2024-07-16 01:24 UTC, pjboudrx commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +If you have Single Sign-On configured for an Organization, and want to use the same email domains with Shared SSO, you will need to migrate.
I still wanted to emphasize the importance of following the steps in this exact order.

2024-07-16 17:43 UTC, pjboudrx commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +6. Transfer claimed Domains from the original Organization to the Admin Organization
The process here is to remove them from the original Organization (not yet linked) to the Admin Organization.
Claimed domains do get hidden in the Linked Orgs once they are linked.

2024-07-16 17:44 UTC, pjboudrx commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +    1. Establish a Group in your IDP for the users who have access to the original Organization
These are sub-steps, and need to be done in this order

2024-07-16 17:44 UTC, pjboudrx commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +8. (optional) Finish setting up SCIM
Just the steps enumerated below. The "SCIM" section explains what's different.

2024-07-16 18:01 UTC, pjboudrx commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +## Migrating To Shared SSO
The pictures are the same as the above section, so I linked to those sections for more detail.

2024-07-30 00:33 UTC, caracheng commented
Couple pieces of feedback:

Overview Section:
- Do we have a screenshot of what an Admin Org would look like? I'm sure we can easily tell an "Admin Org" from a "regular Org" since it's missing the projects, teams, etc...parts but perhaps a screenshot would be helpful for visual learners. 
^^oh wait, I see that we have this at the bottom of the page....can we bring something similar up? 

How It Works section:
- "any Single Sign-On settings or Claimed Domains the Linked Organization may have had are now ignored." << should we bold this, i feel like this might be easy to miss

Differences From Single Organization SSO section:
- I feel like this section might be better as a table vs individual paragraphs. 
- potential typo here?: **I** Shared SSO, SCIM groups in the IDP map to Linked Organizations, with the IDP group name matching the Linked Organization's SCIM Name. 

Setting Up Shared SSO section:
- I wonder if the overview is redundant since a couple lines down, we walk through the steps in more visual detail 
- the links in this section all seem to point to the SCIM section of the SSO doc. I think it should point to the Overview instead. 
- Step 2: Set up SSO for the Admin Organization: I feel like we can reword this slightly. Instead of
> "You do this in Mixpanel and your IDP. This is the same as if it were a regular Organization"
maybe: 
> "Follow the steps to set up SSO in the Admin Org as you would for a regular Org. 

-Step 3: Include some blurb about clicking the "+ Link Organization" button to generate the linking code. Perhaps modify the screenshot to include a subtle box for that button (I def missed this during my first read and asked "how do I generate a link code?")

Migrating to Shared SSO: 
- Step 4: should we bold "do **not** start pushing groups? (Assuming that bad things will happen if they do, want to make this a bit louder)
- Step 6: what does transferring a claimed domain look like? Is there like a transfer button or is this a manual transfer process?

2024-07-30 01:19 UTC, kurbycchua requested changes
left comments

2024-07-30 01:19 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +In single-Organization SSO, SCIM groups in the IDP map to a Team in Mixpanel, using, with the IDP group name matching the Mixpanel Team **name**. I Shared SSO, SCIM groups in the IDP map to Linked Or
maybe can just have these as bullets so it can be indented? and I guess you can still have the table?? Up to you just trying to see how best to have it more visually easy to read.

Also this line "SCIM groups in the IDP map to a Team in Mixpanel" should it be Teams plural since groups is plural and link Teams to /docs/orgs-and-projects/roles-and-permissions#teams

There's also this "using" word that seems out of place. and "I Shared" should be "In Shared"

2024-07-30 01:19 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +2. [Set up SSO](/docs/access-security/single-sign-on/overview#scim) for the Admin Organization as if it were a regular Organization
/docs/access-security/single-sign-on/overview#scim should be /docs/access-security/single-sign-on/overview

2024-07-30 01:19 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +### 2. [Set up SSO](/docs/access-security/single-sign-on/overview#scim) for the Admin Organization
should drop the #scim in the link?

2024-07-30 01:19 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +You do this in Mixpanel and your IDP. This is the same as if it were a regular Organization. [SSO documentation](/docs/access-security/single-sign-on/overview#scim).
same here should drop the #scim

2024-07-30 01:19 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +> ℹ️ With Shared SSO, the SCIM process cannot create, delete or alter the linked Organizations in Mixpanel like it would with a Mixpanel Team. The SCIM process can only add and remove Users, and assi
the last statement "and assign those users to the Organization." maybe have it as "and assign those users to the linked Organization." just to be 100% clear =D

2024-07-30 01:19 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +6. In Mixpanel, transfer claimed Domains from the original Organization to the Admin Organization. Any claimed Domains in a Linked Organization will be hidden.
once in step 2 the SSO is setup - do we not hide the claimed domains for the linked org at this point? Just thinking if we should
1. Mention that they need to note / record down the Claimed Domains of each Org to be linked
2. At Step 2 mention that they don't claim any of the existing domains first (which will be done in step 6)?

2024-07-30 01:19 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +    3. Configure your IDP to push this group to Mixpanel
Do they need to disable the old IDP App that used to push Teams to child orgs?

2024-07-30 01:19 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +An "Admin" Organization is a special type of Organization that contains Single Sign-On settings and Claimed Domains. It can have Organization Members, but you should only add administrative users to
should we add the linked word in this sentence just to be clear

The [SCIM](/docs/access-security/single-sign-on/overview#scim) process will add Users as Linked Organization Members.

2024-07-30 06:03 UTC, themacguffinman approved these changes
LGTM, not a final review but this is good enough to ship on short notice

2024-07-30 06:03 UTC, themacguffinman commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +> ❗ If you use Azure for SSO, you must [open a Mixpanel support ticket](https://mixpanel.com/get-support) before migrating, due to constraints with “Issuer URL” and “Identifier (Entity ID)”
It should be clear that this is only a problem if you have an existing organization using Azure SSO already setup, this isn't a general issue for new SSO users with Azure.

2024-07-30 16:33 UTC, pjboudrx commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +An "Admin" Organization is a special type of Organization that contains Single Sign-On settings and Claimed Domains. It can have Organization Members, but you should only add administrative users to
I don't understand - SCIM is linked. Is there something else?

2024-07-30 16:36 UTC, pjboudrx commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +6. In Mixpanel, transfer claimed Domains from the original Organization to the Admin Organization. Any claimed Domains in a Linked Organization will be hidden.
We only hide claimed domains and SSO settings once the Orgs are linked. I'll try to clarify that.

2024-07-30 16:45 UTC, pjboudrx commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +    3. Configure your IDP to push this group to Mixpanel
Good point - yes, they should because it won't work

2024-07-30 16:48 UTC, pjboudrx commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +6. In Mixpanel, transfer claimed Domains from the original Organization to the Admin Organization. Any claimed Domains in a Linked Organization will be hidden.
And good catch - this step should actually happen earlier.

2024-08-01 01:16 UTC, kurbycchua approved these changes
I'm good with this, just one minor comment on maybe adding one more screen under the Setting Up Shared SSO Step 1, under last statement: "The new Admin Organization will be listed in the left nav in Organization Settings." just for more clarity. I'll leave that for you to decide, not a show stopper.

2024-08-01 01:16 UTC, kurbycchua commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +The new Admin Organization will be listed in the left nav in Organization Settings.
Do we want to just have a screen shot for this point on "The new Admin Organization will be listed in the left nav in Organization Settings"?

2024-08-02 18:22 UTC, pjboudrx commented on pages/docs/access-security/single-sign-on/shared-sso.md
> +The new Admin Organization will be listed in the left nav in Organization Settings.
Added.

2024-08-02 19:23 UTC, merged