Myronkaifung identitymanagement update
mixpanel/docs-legacy pull request #1290
Opened 2024-07-31 22:42 UTC by myronkaifung

2024-08-02 17:31 UTC, myronkaifung commented
tldr

* Overview page added to discuss what is distinct id, example of id management in action, and lightly touch on the 2 API versions
* Identifying users page now only discuss Simplified API, with a callout at the top to check versions and a link to the Original API doc. Focused on implementing and underlying mechanism and not just an overview
* New identifying users page focused only on Original API. Unindexed in the nav bar, only accessible via the call out from the main SImplified page. Focused on implementing and underlying mechanism and not just an overview
* updated redirect so any existing hyperlinks should continue to work

2024-08-05 06:36 UTC, kurbycchua requested changes
I have placed my suggestions and comments inline. Overall I like this new way of documenting ID Merge and also splitting out the Original vs Simplified as separate pages with Original being hidden. You actually beat me to it, since I had this in my backlog. Thus thank you for driving this and for asking me to review, now I can focus on other things.

I tried my best to put the same comments for the simplifies vs original pages which are somewhat similar, I might miss some things so do double check for comments on once side that might apply to the other. Once you're done happy to have a 2nd review before I approve it.

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identity-management.mdx
> +The Distinct ID is the identifier property that Mixpanel uses to keep identify your users. Every event data and profile update sent to Mixpanel should have a distinct_id property associated with it (
For this sentence: "The Distinct ID is the identifier property that Mixpanel uses to keep identify your users." maybe we can reword to "Distinct ID is Mixpanel's identifier used to uniquely track a user in the system."

One note which I struggle as well when I update docs on distinct_id is that /import and /track uses distinct_id but /engage uses $distinct_id (as well as our UI). Which is why in the Reserved Event Properties page I decided to put both https://docs-git-myronkaifung-identitymanagement-update-mixpanel.vercel.app/docs/data-structure/events-and-properties#reserved-event-properties Not a big deal but just something to note. I think we can leave it as distinct_id

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identity-management.mdx
> +**User Analytics** - Distinct IDs are used to index individual users. If a single users is tracked using 2 different Distinct IDs, they will appear as 2 different users in your project.
In this case "User Analytics" is not really a report when compared to Insights and Funnels? I would suggest maybe changing this to say Users report to explain User Profiles where with 2 different Distinct IDs the same user would end up with 2 different profiles (which is quite common among many customers)? This paragraph is kinda a repeat anyway of what we already stated above in the call out on events having 2 different Distinct ID values.

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identity-management.mdx
> +<img src="/no_id_management.png" alt="no_id_management" width="400"/>
Would be nice if you can make the image background transparent so that it blends in with the doc background, looks more professional with diagrams. Let me know if you need help on this. Happy to do it.

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identity-management.mdx
> +3. This single user would appear as two separate users in your Mixpanel project; once or their access through the website, and another for their access through your app.
missing "f" in "once or their" or should be for

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identity-management.mdx
> +![with_id_management](/with_id_management.png)
same comment for image background

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identity-management.mdx
> +2. When the user registers for an account, your implementation make an identify call, using their name `charlie` as the User ID. This triggers an ID merge, resulting in an ID cluster containing both
this "your implementation make" I think should be "your implementation makes"

Also thinking instead of saying "using their name `charlie`" shall we say "using their login `charlie`" to avoid the notion of like using names but logins

this "containing both `charlier` and `123`" should be "containing both `charlie` and `123`" without the extra "r" at charlie

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identity-management.mdx
> +With identity management, a user who accesses your product from multiple devices are accurately resolved to a single user.
I think "accesses" should just be "access"

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identity-management.mdx
> +Mixpanel supports 2 versions of the ID Merge API; Simplified ID Merge and Original ID Merge. Simplified ID Merge API is the default for new organizations.
Suggestion:

Mixpanel supports 2 versions of the ID Merge API:
- Simplified ID Merge
- Original ID Merge

Simplified ID Merge API is the default for all new organizations created from April 2024.

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identity-management.mdx
> +Due to the limited changes in functionality beyond a simpler implementation experience, we do not recommend that customers who have already implemented using the original API reimplement on the simpl
I know you copied this from the original docs, but thinking since this paragraph is quite confusion and contradictory where in we say "we do not recommend" yet we have docs on how to migrate to simplified, should we just say (from the last line above)

Simplified ID Merge API is the default for new organizations created from April 2024. Although it is not directly possible to switch from Original ID Merge (for a project that already has data) to Simplified ID Merge, both APIs will remain supported.

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identity-management.mdx
> +Once there are any data in your project, your Identity API version cannot be changed.
Instead of "Once there are any data in your project, your Identity API version cannot be changed." we can say "A project's Identity Merge API version setting cannot be changed once you start sending data into the project."

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identity-management.mdx
> +- The distinct_id is automatically determined by Mixpanel using one of the IDs in the cluster and is not user-configurable. Any IDs in the cluster can be used for ingestion.
Just thinking if we should still mention this "Any IDs in the cluster can be used for ingestion." since it kinda implies that Simplified doesn't since we didn't mention it there.

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identity-management.mdx
> +- mParticle works out of the box with both the original API, and the Simplified API; when using the Simplified API (for new projects) ensure the "Simplified ID Merge" option is checked in mParticle's
capitalize "O" in "original API" since you capitalized "S" or maybe make it consistent with the rest of the bullets in this section where it's lowecase with the exception of "Simplified ID Merge" in quotes.

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identity-management.mdx
> +Most other integrations are unaffected by this API change. These integrations are not involved in identity management, they send data to the ID they are given and will work the same way on the simpli
Not sure why in the preview the "Most other integrations..." paragraph got stuck to the previous bullet. Maybe because there is a missing period at the end of the last bullet?

This "will work the same way on the simplified API that they do on the original API." should be "will work the same way on the simplified API as they do on the original API."

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-simplified.mdx
> +The `distinct_id` property (learn more [here](/docs/tracking-methods/id-management/overview#distinct-id)) is the identifier property that Mixpanel uses to determine the uniqueness of your users.
should the link be docs/tracking-methods/id-management/identity-management#distinct-id

Also "The `distinct_id` property is the identifier property that Mixpanel uses to determine the uniqueness of your users." you can drop the 2nd "property" after identifier since you already said property just before

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-simplified.mdx
> +Calling `identify(<user_id>)` sets the `user_id` value passed to the identify function as the `$user_id` event property for the user's events moving forward.
for this "Calling `identify(<user_id>)` sets" should we say "Calling `identify(<user_id>)` in Mixpanel SDKs sets" since in APIs identify does not exist for simplified

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-simplified.mdx
> +    | 5     | D2         | U2       | U2                            | Links D2 ⇒ U2, D1, D2, and U1 are inside one ID cluster              |
this is wrong "D1, D2, and U1 are inside one ID cluster" should be "D1 and U1 are inside one ID cluster and D2 and U2 are inside a totally separate cluster" Or just simply say "D2 and U2 are inside one ID cluster"

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-simplified.mdx
> +If you choose to manually define the `distinct_id` property, it should be the same value as the `$user_id`.
hmm thinking maybe we should drop this line as it might create confusion?

"If you choose to manually define the `distinct_id` property, it should be the same value as the `$user_id`." since a reader might think they can set distinct_id = $device_id without the prefix which would end up a disaster

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-simplified.mdx
> +Here's a pseudocode example using Django's [cookies](https://django-book.readthedocs.io/en/latest/chapter14.html#cookies) and [authentication](https://django-book.readthedocs.io/en/latest/chapter14.h
I can't seem to access those links it's says 404 for both link

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-simplified.mdx
> +  track_to_mp(request, "$identify", properties)
Hmm not quite sure about this code in simplified all identity events ($identify, $create_alias, $merge) will be ignored at ingestion as per my test previously thus sending $identify will not be processed. Did you try this code in a project with simplified ID merge? Maybe should change the event from "$identify" to just as "add_to_cart"

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-simplified.mdx
> +Set the `$user_id` property to the Authenticated ID and continue setting `$device_id` to the Anonymous ID generated in step 1, including both the `$user_id` and `$device_id` in your events moving for
This is just a note, once $device_id and $user_id is merged, technically there is no need to keep sending $device_id in subsequent events and customer can just use $user_id. Thus you just need 1 event with both $device_id and $user_id to trigger the merge, any subsequent event while user is know can just be $user_id without the $device_id. Anyway just a note

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-simplified.mdx
> +**Call `.identify` upon a registration/login or when an app is re-opened in a logged-in state**
It's important to note that for simplified, identify and reset only exists in client-side SDKs to set / reset $user_id in the cookie. Just thinking since we are in the midst if improving this, should we just state "Call `.identify` in Mixpanel's client-side SDK upon..."

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-simplified.mdx
> +**Call `.reset` upon logout or when an app leaves an authenticated-state**
Same comment as previous point on calling identify

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-simplified.mdx
> +By calling `.reset()` at logout or when a user enters an unauthenticated-state (such as timing out), you generate a new `$device_id` for your user, ensuring that multiple users that are sharing a sin
the word "incorrect" should be "incorrectly"

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-simplified.mdx
> +See the SDK reference on [registering super properties](/docs/tracking-methods/sdks/javascript#super-properties) and [setting profile properties](docs/tracking-methods/sdks/javascript#setting-profile
this "docs/tracking-methods/sdks/javascript#setting-profile-properties" should be "/docs/tracking-methods/sdks/javascript#setting-profile-properties"

The missing / infront will result to a broken link

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-simplified.mdx
> +It is not possible to merge 2 `$user_id`s together using the Simplified API. We don't recommend doing this in general, as it adds complexity to your identity resolution strategy. Instead, we recommen
I had plans to edit this line "Instead, we recommend having a single, unchanging `$user_id` for each user and pointing all other IDs for that user to that single `$user_id`" to

"Instead, we recommend having a single, unchanging `$user_id` for each user and pointing all other IDs (as $device_ids) for that user to that single `$user_id`."

See if it makes sense to you

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-simplified.mdx
> +For cohort syncs out to 3rd-party systems, we recommend designating a user property with the identifier of the user in that third-party system. More details are in our [integrations docs](/docs/cohor
The link /docs/cohort-sync/integrations/braze maybe can be more specifically link to /docs/cohort-sync/integrations/braze#matching-mixpanel-and-braze-users

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-simplified.mdx
> +
I noticed that the last FAQ in the original document that talks about $identity_failure_reason was not included. We should still include that as it is still valid for Simplified. You can copy paste below:

**Why is there a `$identity_failure_reason` and `$distinct_id_before_identity` in my event?**

The `$identity_failure_reason` property will be populated with a value `errAnonDistinctIdAssignedAlready` if the `$device_id` passed was already linked to another `$user_id`. The `$device_id` will be ignored and the `$user_id`, in the same event, will be used as the `distinct_id` for the event. 

The `$distinct_id_before_identity` property stores the original `distinct_id` (which was `$device:<value for $device_id>`) when the event was sent to Mixpanel before being mapped to the `$user_id`.

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +# Identifying Users
Just thinking if we should make this "Identifying Users (Original API)" reason is that as I was clicking on the callout links to go from Simplified to Original (and vice versa) the page was looking exactly the same to me at first look. I know the 2 pages are somewhat similar, but making the title heading more obvious might help before I start reading the content in case I was at the wrong page?

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-simplified.mdx
> +# Identifying Users
Just thinking if we should make this "Identifying Users (Simplified API)" reason is that as I was clicking on the callout links to go from Simplified to Original (and vice versa) the page was looking exactly the same to me at first look. I know the 2 pages are somewhat similar, but making the title heading more obvious might help before I start reading the content in case I was at the wrong page?

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +The **Original ID Merge API** uses three special events to link identities and set the `distinct_id` for your events; `$identify`, `$create_alias`, and `$merge` events.
"The **Original ID Merge API** uses three special events to link identities and set the `distinct_id` for your events; `$identify`, `$create_alias`, and `$merge` events." 

some minor grammar corrections:

The **Original ID Merge API** uses three special events to link various user identifiers and sets the `distinct_id` for your events; these events are namely: `$identify`, `$create_alias`, and `$merge`.

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +The `$identify` event will only merge an `$anon_id` that is in UUIDv4 format (anonymous ID format generated by Mixpanel and Segment) and only if the $anon_id was not previously merged to another `$id
make $anon_id as `$anon_id` as I think without the ` it creates weird formatting with the $ sign

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +- something about identify event properties (failure reason, identified_id, id_before_identify, etc.)
was this left so you could expand how to troubleshoot Original ID merge? Seems like a dangling sentence

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +The `$create_alias` event is used to create an alias. An alias is a new value that will be interpreted by Mixpanel as an existing value. This is triggered when calling `.alias` using the client-side
Hmm this sentence: "The `$create_alias` event is used to create an alias. An alias is a new value that will be interpreted by Mixpanel as an existing value. This is triggered when calling `.alias` using the client-side SDKs." does not make sense, maybe you can say 

The `$create_alias` event can be used to link two non-anonymous Distinct IDs. It creates an “alias” to another Distinct ID already present in the identity cluster and adds the same alias ID into the same cluster. This is triggered when calling `.alias` using the client-side SDKs.

refer to my this deck for inspiration: https://docs.google.com/presentation/d/1_4oKGzO3evq1yBKntyQUvBGcA-OcWDTy_oxQbgzxtV0/edit#slide=id.gf8d0d12897_0_3652

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +This event is not triggered using any SDK functions; it can only be imported by calling the API directly. Learn more in our API reference [here](https://developer.mixpanel.com/reference/identity-merg
change: "This event is not triggered using any SDK functions; it can only be imported by calling the API directly. Learn more in our API reference [here](https://developer.mixpanel.com/reference/identity-merge)."

to: This event cannot be triggered using any SDK methods; it can only be processed when sent via the /import API directly. Learn more in our API reference [here](https://developer.mixpanel.com/reference/identity-merge).

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +2. Call `.reset()` when a user logs out.
So in Original ID Merge, we generally do not recommend calling reset() since this would easily cause a user to hit 500 cluster, especially for websites / apps with timeout logouts. 

see: https://docs.google.com/presentation/d/1_4oKGzO3evq1yBKntyQUvBGcA-OcWDTy_oxQbgzxtV0/edit#slide=id.g106726c6eaa_0_60

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +- Calling `.reset` will clear the local storage (which contains the `$user_id` and `$device_id`), and generate a new `$device_id` for the session. It is recommended to call `.reset` when a user logou
see comment above on reset(), best NOT to call reset, the only drawback of not calling reset is that any post-logout anonymous events will be linked to the previous user. If we want to recommend calling reset() I tend to recommend calling it when there is an explicit action to signup for a new account (ie clicking on Sign-up Button) so that any signup flow can be tied to the new user instead of the previous logged out user

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +    The `distinct_id` is randomly selected by Mixpanel using the IDs inside of an identity cluster. This means that the canonical distinct_id could be set to a `$device_id` or your chosen `user_id`.
instead of saying "randomly" we should say "programatically" so something like:

The `distinct_id` is programatically selected by Mixpanel, using one of the IDs inside of an identity cluster, based on the most optimal merging process.

see: https://docs.google.com/presentation/d/1_4oKGzO3evq1yBKntyQUvBGcA-OcWDTy_oxQbgzxtV0/edit#slide=id.g1029aef1f24_0_399

Also this line "but only the canonical `distinct_id` is used in queries and exports." we can say "but only the canonical `distinct_id` can be used in queries and exports."

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +Let's walk through a few user flows where ID Merge is useful, and when to call `.identify()` and `.reset()` to use ID Merge properly.
see comment on reset() maybe this is a good section to highlight when should reset be called to avoid hitting 500 limit

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +### New User Signup
Would be nice to have the visual tables similar to the simplified ones. Happy to help with those.

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +2. The user returns later and signs up for your product. You call `.identify(U1)`. Mixpanel adds U1 and D1 to the same identity cluster. Moving forward, any events tracked using either U1 or D1 will
avoid the word "randomly" as per previous comment

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +1. The user from the previous flow returns, but is on a new device and has not logged in yet. Our SDK assign the user a random `$device_id` (D2) and persists it. All events tracked at this point will
"Our SDK assigns" assign should be with "s"

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +2. The user logs in and call `.identify(U1)` to tell us that the user on this device is the same user we have seen before. Mixpanel adds D2 to the identity cluster previous created (D1+U1). Moving fo
"The user logs in and call `.identify(U1)` to tell us.."

maybe as: "The user logs in and a call to `.identify(U1)` is made to tell us..."

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +2. The user logs in and call `.identify(U1)`, which links the D1 and U1 to the same identity cluster.
"The user logs in and call .identify(U1), which links.."

maybe as: "The user logs in and a call to .identify(U1) is made, which links..."

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +3. The user logs out. At this point, you should call `.reset()`, or manually generate a new `$device_id` if you are managing it yourself. A new user shows up and tracks events using this new `$device
We should perhaps completely reword expand this example to:

3. The user logs out. At this point, any events triggered will still be linked to U1. We don't call `.reset()` at this point since we do not know if this is the same user or a totally different user. Not calling `.reset()` at this point also prevents hitting the 500 ID cluster limit should the same user log back in there will be be new `$device_id` to link into the cluster.

4. A different new user shows up and clicks "Sign-up" button on the same device. Before triggering any event we call `.reset()` to force the clearing of `distinct_id` and to generate a new random `$device_id` (D2). This would help us to link any anonymous events as part of the sign-up flow to the new user instead of the previous logged out user.

5. This new user (U2) now completes sign-up and logs in as a separate user. Call `.identify(U2)` which will now link D2 and U2 to form one cluster. D1 and U1 remains as a separate cluster.

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +4. This new user (U2) now logs in as a separate user. Call `.identify(U2)`. Now D2 and U2 are merged to form one cluster. D1 and U1 remains a separate cluster.
see previous comment to change 4. to 5.

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +When using our Web or Mobile SDKs, Mixpanel will automatically generate an `$device_id` that's local to that user's device, and set that value as the `distinct_id` for the event. This ID will persist
"Mixpanel will automatically generate an `$device_id`" should be 

"Mixpanel will automatically generate a `$device_id`"

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-simplified.mdx
> +When using our Web or Mobile SDKs, Mixpanel will automatically generate an `$device_id` that's local to that user's device, and set that value as the `distinct_id` for the event. This ID will persist
"Mixpanel will automatically generate an $device_id" should be

"Mixpanel will automatically generate a $device_id"

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +Set the `distinct_id` event property to the anonymous ID you generated. You do not need to set the `$device_id` property.
suggestion: "You do not need to set the `$device_id` property."

maybe: "You do not need to set the `$device_id` property explicitly; although recommended should you want to track users using multiple or sharing devices"

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +Merge the users together by importing the `$identify` event.
sould we say "Merge the IDs together by sending the `$identify` event."

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +**Call `.reset` upon logout or when an app leaves an authenticated-state**
Maybe modify to: **Call `.reset` only when there is an explicit intent to change to a new user (ie clicking on Sign-up button)**

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +By calling `.reset()` at logout or when a user enters an unauthenticated-state (such as timing out), you generate a new `$device_id` for your user, ensuring that multiple users that are sharing a sin
Maybe modify to: By calling `.reset()` only when there is an explicit intent to change to a new user, allows you to link any anonymous events, that may be important as part of a user journey, to the new user instead of the previously logged out user. This would also avoid unnecessarily hitting the 500 ID cluster limit when the same previous user simply logs back in since no new `$device_id` is generated.

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +See the SDK reference on [registering super properties](/docs/tracking-methods/sdks/javascript#super-properties) and [setting profile properties](docs/tracking-methods/sdks/javascript#setting-profile
this "docs/tracking-methods/sdks/javascript#setting-profile-properties" should be "/docs/tracking-methods/sdks/javascript#setting-profile-properties"

The missing / infront will result to a broken link

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +The canonical distinct_id is randomly selected by Mixpanel using any of the IDs inside of a cluster. This means that even after identifying your user, Mixpanel may choose your user ID or one of the o
1. avoid using the word "random" as per previous comments.

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +Any IDs inside of the cluster can be used for ingestion and will resolve to the same user in Mixpanel, but only the canonical distinct_id is used in queries and exports.
"but only the canonical distinct_id is used in queries and exports." to

"but only the canonical distinct_id can be used in queries and exports."

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +**Is it possible to merge two `$identified_id`s?**
maybe change "`$identified_id`s" to just "Identified IDs" so as not to confuse with $identify's parameter

2024-08-05 06:36 UTC, kurbycchua commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +For cohort syncs out to 3rd-party systems, we recommend designating a user property with the identifier of the user in that third-party system. More details are in our [integrations docs](/docs/cohor
The link /docs/cohort-sync/integrations/braze maybe can be more specifically link to /docs/cohort-sync/integrations/braze#matching-mixpanel-and-braze-users

2024-08-08 07:19 UTC, myronkaifung commented on pages/docs/tracking-methods/id-management/identity-management.mdx
> +The Distinct ID is the identifier property that Mixpanel uses to keep identify your users. Every event data and profile update sent to Mixpanel should have a distinct_id property associated with it (
Done. Making the callout about distinct_id vs $distinct_id instead.

2024-08-08 17:40 UTC, myronkaifung commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +2. Call `.reset()` when a user logs out.
I will add a callout for the reset and 500 limit, but going to leave the content the same since it is important to call reset at logout to prevent merging of the same multiple users on same device.

2024-08-08 17:43 UTC, myronkaifung commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +- Calling `.reset` will clear the local storage (which contains the `$user_id` and `$device_id`), and generate a new `$device_id` for the session. It is recommended to call `.reset` when a user logou
done using your recommended language in the slides

2024-08-08 17:51 UTC, myronkaifung commented on pages/docs/tracking-methods/id-management/identifying-users-original.mdx
> +3. The user logs out. At this point, you should call `.reset()`, or manually generate a new `$device_id` if you are managing it yourself. A new user shows up and tracks events using this new `$device
Done. Great suggestion

2024-08-08 20:07 UTC, merged