Update cohort-sync.md to have info in Delay in Sync
mixpanel/docs-legacy pull request #1562
Opened 2024-10-23 06:23 UTC by naitik-mixpanel

Added text for "Delay in sync". Need to update image

2024-10-23 07:06 UTC, kurbycchua requested changes

2024-10-23 07:06 UTC, kurbycchua commented on pages/docs/cohort-sync.md
> +If you notice that cohorts which are recurring in sync are taking more than expected time to sync, we recommned to have mutliple connections created and have cohorts spread across these connections.
maybe:

If your recurring cohort syncs are taking more time than expected, we recommend creating multiple connections and spreading your syncs across them. Cohort syncs under one connection are executed in a sequential order; to increase parallelism, you should create multiple connections covering different types of sync.

In general, if you see the cumulative user count of all cohorts synced under a connection breach ~5 million, we would recommend that you create a new connection.

2024-10-23 07:06 UTC, kurbycchua commented on pages/docs/cohort-sync.md
> +All cohorts in a connection are queued in a sequential order while the connections run in parallel which could be the reason for cohorts to have a delay in sync. If you see the cumulative user count
I guess you can delete this since I've move it up?

2024-10-24 09:15 UTC, argenisf approved these changes
LGTM

2024-10-28 06:14 UTC, kurbycchua approved these changes

2024-10-28 06:16 UTC, merged