Stage reference changes to readme
mixpanel/docs-legacy pull request #602
Opened 2023-10-10 17:06 UTC by tiffanyqi

2023-10-10 22:14 UTC, tiffanyqi commented on .github/workflows/rdme-delete-staging.yml
> +name: Delete ReadMe Staging
workflow untested. how does this look?

2023-10-10 22:14 UTC, tiffanyqi commented on .github/workflows/rdme-staging.yml
> +          npm install -g rdme
is this the right command? is it ok to install rdme globally each time this workflow runs?

2023-10-10 22:15 UTC, tiffanyqi commented on .github/workflows/rdme-staging.yml
> +          fi
is this the right way to check whether the version already exists? tbh, i got this from chat gpt, so i'm unsure if this is up to date / too much!

2023-10-10 22:16 UTC, tiffanyqi commented on .github/workflows/rdme-staging.yml
> +  preview-notify:
took this whole section from the marketing-site yaml. the only thing I modified here was in `sparse-checkout` and the api reference preview link.

2023-10-10 22:18 UTC, tiffanyqi commented
@austinpray-mixpanel how do I remove the `push` workflows on both rdme-staging and preview / notify? i think the only way to get the pull request numbers is to set them as such in `on`, but when i move the branches-ignore to `pull_request`, the workflow wouldn't run at all

2023-10-10 22:34 UTC, austinpray-mixpanel requested changes

2023-10-10 22:34 UTC, austinpray-mixpanel commented on .github/workflows/rdme-staging.yml
> +      - main
```suggestion
```

you can omit this entirely and it will run on all pull_request updates

2023-10-10 22:34 UTC, austinpray-mixpanel commented on .github/workflows/rdme-staging.yml
> +      has-version: ${{ steps.check-readme-version.outputs.has-version }}
what is this for?

2023-10-10 22:34 UTC, austinpray-mixpanel commented on .github/workflows/rdme-staging.yml
> +          if rdme versions --version=${{ github.event.number }} --key=${{ secrets.README_API_KEY }}; then
I expected something like `--version=pr${{ github.event.number }`

2023-10-10 22:34 UTC, austinpray-mixpanel commented on .github/workflows/rdme-staging.yml
> +          fi
Do it like this https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-setting-an-output-parameter

use $GITHUB_OUTPUT instead of GITHUB_ENV

2023-10-10 22:34 UTC, austinpray-mixpanel commented on .github/workflows/rdme-staging.yml
> +          rdme: docs ./reference --key=${{ secrets.README_API_KEY }} --version=${{ github.event.number }}
I expected `--version=pr${{ github.event.num }}` so the version number is like vpr123 instead of v123

2023-10-10 22:34 UTC, austinpray-mixpanel commented on .github/workflows/rdme-staging.yml
> +  preview-notify:
yup looks good! sparse checkout is less relevant for tiny docs repo but can't hurt!

2023-10-10 22:38 UTC, tiffanyqi commented on .github/workflows/rdme-staging.yml
> +      has-version: ${{ steps.check-readme-version.outputs.has-version }}
i don't know, i left this here because that's what chat gpt contained lol. ultimately, i need to check to see if readme has already created a new version, so that's what the `if` checks were for on line 35. do i need the above line in conjunction with that line 35 block?

2023-10-10 22:38 UTC, tiffanyqi commented on .github/workflows/rdme-staging.yml
> +          if rdme versions --version=${{ github.event.number }} --key=${{ secrets.README_API_KEY }}; then
sure! i can modify that.

2023-10-10 22:42 UTC, tiffanyqi commented on .github/workflows/rdme-staging.yml
> +          fi
like this?
```
        run: |
          if rdme versions --version=pr${{ github.event.number }} --key=${{ secrets.README_API_KEY }}; then
            echo "has-version=true" >> "$GITHUB_OUTPUT"
          else
            echo "has-version=false" >> "$GITHUB_OUTPUT"
          fi

```

what's the difference here? would I have to modify anything else to use this?

2023-10-10 22:44 UTC, austinpray-mixpanel commented on .github/workflows/rdme-staging.yml
> +      has-version: ${{ steps.check-readme-version.outputs.has-version }}
Then it's not needed. You can just do like the example here: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-setting-an-output-parameter

2023-10-10 22:58 UTC, austinpray-mixpanel commented on .github/workflows/rdme-staging.yml
> +        if: steps.has-version.outputs.has-version == 'false'
```suggestion
        if: steps.check-readme-version.outputs.has-version == 'false'
```

2023-10-10 22:58 UTC, austinpray-mixpanel commented on .github/workflows/rdme-staging.yml
> +          npm install -g rdme
yeah it's okay to install globally but I would prolly pin the version in a package.json

2023-10-10 23:07 UTC, tiffanyqi commented on .github/workflows/rdme-staging.yml
> +          npm install -g rdme
our `rdme` package is pinned in package.json to 8.6.6, is that enough in this case here?

2023-10-11 02:25 UTC, tiffanyqi commented on .github/workflows/rdme-staging.yml
> +          rdme: docs ./reference --key=${{ secrets.README_API_KEY }} --version=0.0-pr-${{ github.event.number }}
sorry for all of the commits / pushes! this is the only thing that changed from last you looked

2023-10-11 15:08 UTC, austinpray-mixpanel commented on .github/workflows/rdme-delete-staging.yml
> +name: Delete ReadMe Staging
This looks like it should work fine. If it doesn't work or is too hard to develop we can just turn this into a cron that looks for versions like 0.0-pr-$PR_NUMBER and then for every $PR_NUMBER check if it's merged and delete if so.

2023-10-11 15:21 UTC, austinpray-mixpanel commented on .github/workflows/rdme-staging.yml
> +          npm install -g rdme
PRed your PR here https://github.com/mixpanel/docs/pull/608

2023-10-11 15:22 UTC, austinpray-mixpanel requested changes
PRed your PR https://github.com/mixpanel/docs/pull/608

2023-10-11 15:22 UTC, austinpray-mixpanel commented on .github/workflows/rdme-delete-staging.yml
> +      rdme: versions:delete 0.0-pr-${{ github.event.number }} --key=${{ secrets.README_API_KEY }}
Oh should probably check that the version exists before deleting huh?

You can wrap this in a little bash script so you can test outside of the action

2023-10-11 18:32 UTC, austinpray-mixpanel commented on .github/workflows/rdme-delete-staging.yml
> +      - 'reference/**'
```suggestion
```

This looks like wrong indention. And I would just run this always anway.

2023-10-11 18:35 UTC, tiffanyqi commented on .github/workflows/rdme-delete-staging.yml
> +      - 'reference/**'
but wouldn't it be better to do so only a PRs that created the staging env in the first place? (will def fix the indention, was going to push it!)

2023-10-11 18:40 UTC, austinpray-mixpanel commented on .github/workflows/rdme-delete-staging.yml
> +      - 'reference/**'
Yeah it would be, would need to match the parent workflow's paths for that to not leak versions

![image](https://github.com/mixpanel/docs/assets/71290498/d1cef2a6-5414-4228-adf4-2b60cc66e8ca)

2023-10-11 18:45 UTC, austinpray-mixpanel approved these changes
lgtm!

2023-10-11 19:02 UTC, merged