Create aws-kafka.md
mixpanel/docs-legacy pull request #624
Opened 2023-10-18 02:48 UTC by lohking

docs for kafka>mixpanel

2023-10-18 15:35 UTC, ranic commented
thanks for doing this @lohking! let's not merge this until we have someone from engineering tal at this first

2023-10-20 23:02 UTC, myronkaifung commented
Awaiting review from engineering

2023-10-25 23:51 UTC, myronkaifung requested changes
I would recommend double-checking the file path again before merging as the nesting has changed since the release of new nav (suggestion: docs/pages/docs/tracking-methods/integrations/). Other than that, please have someone from Eng review the content itself prior to merging as per Vijay's suggestion

2024-01-12 23:01 UTC, csiden commented on pages/docs/tracking/integrations/aws-kafka.md
> +        mp.track('some_user_id', 'My Event', {'message': event_data})
This looks like it's showing a whole item taken off kafka being set as a single event property called `message`? I think that would be a bad example to give, I know this is for hypothetical data, but maybe we could show an example of taking a few properties off of `event_data` and setting them as explicit properties on the event being tracked so people following the doc know not to track the entire event as a single property?

2024-04-23 16:59 UTC, myronkaifung commented
Hi @lohking wanted to check in on this PR. Are we still looking for Eng review for this PR?

2024-08-15 15:12 UTC, lohking commented
@myronkaifung sorry i missed this! Yes, currently awaiting Eng review to PR.

2024-08-15 16:04 UTC, myronkaifung commented
> @myronkaifung sorry i missed this! Yes, currently awaiting Eng review to PR.

Awesome thanks. Let me know if we need to flag this for attention. Let's get this published!

2024-08-15 16:38 UTC, lohking commented
We've gotten customers asking for docs kafka. Could I trouble you to escalate this to the right person to review? :)​
  
On Aug 16 2024, at 12:05 AM, myronkaifung  ***@***.***>  wrote:
  
>
>   
>   
> >   
> > @myronkaifung (https://github.com/myronkaifung)  sorry i missed this! Yes, currently awaiting Eng review to PR.
> >   
>   
> Awesome thanks. Let me know if we need to flag this for attention. Let's get this published!
>   
>   
> —
>   
> Reply to this email directly,     view it on GitHub (https://github.com/mixpanel/docs/pull/624#issuecomment-2291608623), or     unsubscribe (https://github.com/notifications/unsubscribe-auth/ABKHFTVEYHFCIHHIPVA7ZF3ZRTGTDAVCNFSM6AAAAAA6EY3MKOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOJRGYYDQNRSGM).
>   
> You are receiving this because you were mentioned.
>   
>

2024-08-15 17:45 UTC, myronkaifung commented
@lohking added a comment about the event_data payload. Gonna deploy this today

2024-08-15 17:53 UTC, myronkaifung approved these changes
Added comment to code example. Let's ship for now and update the payload later on

2024-08-15 17:53 UTC, merged